# Copyright Siemens AG, 2014-2018
# SPDX-License-Identifier:	GPL-2.0 LGPL-2.1

# build FOSSology on Travis CI - https://travis-ci.org/

language: php
dist: trusty
php:
  - 7.0
  - 5.6
  - 7.1
addons:
  apt:
    packages: &default_packages
      - bzip2
      - cabextract
      - cpio
      - genisoimage
      - libboost-program-options-dev
      - libboost-regex-dev
      - libcppunit-dev
      - libcunit1-dev
      - libdbd-sqlite3-perl
      - libglib2.0-dev
      - liblocal-lib-perl
      - libmagic-dev
      - librpm-dev
      - libspreadsheet-writeexcel-perl
      - libtext-template-perl
      - php5-cli
      - php5-pgsql
      - poppler-utils
      - p7zip
      - p7zip-full
      - rpm
      - sleuthkit
      - unrar-free
      - unzip
      - upx-ucl

services: postgresql

sudo: required

install:
  - composer install --working-dir=src
  - ./install/scripts/install-spdx-tools.sh
  - ./install/scripts/install-ninka.sh

before_script:
  - ./utils/prepare-test -afty

env:
  global:
    - PHPTESTSUITE=''
    - CHECKBEFORE='cppcheck -q -isrc/nomos/agent_tests/testdata/NomosTestfiles/ -isrc/testing/dataFiles/ --suppress=*:src/copyright/agent/json.hpp src/'
    - MAKETARGETS='all test'
  matrix:
    - PHPTESTSUITE='Fossology PhpUnit Test Suite' CHECKBEFORE='' MAKETARGETS='build-lib VERSIONFILE build-cli'

script:
  - set -e
  - src/testing/syntax/syntaxtest.sh
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then composer require --no-update phpunit/phpunit ^5; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then composer require --dev --no-update phpunit/phpunit ^6; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then composer require --dev --no-update phpunit/phpunit ^7; fi
  - if [[ ! -z "${CHECKBEFORE}" ]]; then ${CHECKBEFORE}; fi
  - if [[ ! -z "${MAKETARGETS}" ]]; then make ${MAKETARGETS}; fi
  - if [[ ! -z "${PHPTESTSUITE}" ]]; then src/vendor/bin/phpunit -csrc/phpunit.xml --testsuite="${PHPTESTSUITE}"; fi
  - set +e

after_script:
  - mkdir -p build/logs
  - if [[ ! -z "${PHPTESTSUITE}" ]]; then php src/vendor/bin/coveralls -vv -x clover.xml; fi

matrix:
  include:
  ## docker tests ##
    - name: default-docker-test
      services: docker
      install: true
      before_script: true
      script: src/testing/docker/default-docker-test.sh
    - name: docker-compose-test
      services: docker
      install: true
      before_script: true
      script: src/testing/docker/docker-compose-test.sh
  ## C/C++ agent tests ##
    - env: CC=gcc-4.8 CXX=g++-4.8 CFLAGS='-Wall'
      addons:
        apt:
          packages:
            - *default_packages
            - gcc-4.8
            - g++-4.8
    - env: CC=gcc-5 CXX=g++-5 CFLAGS='-Wall'
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - *default_packages
            - gcc-5
            - g++-5
    - env: CC=gcc-6 CXX=g++-6 CFLAGS='-Wall'
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - *default_packages
            - gcc-6
            - g++-6
    - env: CC=clang-3.6 CXX=clang++-3.6 CFLAGS='-Wall -Werror -Wno-error=deprecated-register'
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty
          packages:
            - *default_packages
            - clang-3.6
  ## PHP: phpcpd ##
    - script: src/vendor/bin/phpcpd src/cli/ src/copyright/ src/decider*/ src/lib/ src/monk/ src/nomos/ src/readmeoss/ src/spdx2/ src/www/
  allow_failures:
    - script: src/vendor/bin/phpcpd src/cli/ src/copyright/ src/decider*/ src/lib/ src/monk/ src/nomos/ src/readmeoss/ src/spdx2/ src/www/
    - php: 7.1
